[template]
cargo_generate_version = ">=0.23"
ignore = [".github", "scripts", "tests", "target", "Cargo.lock", ".env", "README.md"]

[placeholders]
kit_version = { type = "string", prompt = "Barrzen Axum Kit version", default = "0.1.5" }

[hooks]
post = ["hooks/post-script.rhai"]
